/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package botonesimagenes;

import java.util.Arrays;
import java.util.Collections;
import java.util.Random;

/**
 *
 * @author ESTUDIANTE19
 */
public class matriz extends javax.swing.JFrame {

    /**
     * Creates new form matris
     */
    public matriz() {
        initComponents();
    }
   public int Com = 0,Com1 = 0;
   public int matriz1[][];
   int numero = 0,numero1 = 0;
   StringBuilder generarStringBuilder = new StringBuilder();
   public int a,b;
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        matriz = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        L1 = new javax.swing.JTextField();
        L2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Numeros = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        resul = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Matriz");

        matriz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        matriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizActionPerformed(evt);
            }
        });

        jLabel2.setText("L1");

        L1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1ActionPerformed(evt);
            }
        });

        L2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2ActionPerformed(evt);
            }
        });

        jLabel3.setText("L2");

        b2.setText("GENERAR");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        Numeros.setColumns(20);
        Numeros.setRows(5);
        jScrollPane1.setViewportView(Numeros);

        jLabel4.setText("Recorrido");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ESTUDIANTE02\\Downloads\\Captura_de_pantalla_2024-04-22_134454-removebg-preview (1).png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar Recorrido");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resul, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriz, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(b2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizActionPerformed

    private void L1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L1ActionPerformed

    private void L2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
  
    
    
    
   Random aleatorio = new Random();
 Com = Integer.parseInt(this.L1.getText());
 Com1 = Integer.parseInt(this.L2.getText());

 numero = Integer.parseInt(matriz.getSelectedItem().toString());
 numero1 = Integer.parseInt(matriz.getSelectedItem().toString());
 matriz1 = new int[numero][numero1];



for( a = 0; a < matriz1.length; a++) {
    for( b = 0; b < matriz1[a].length; b++) {
        matriz1[a][b] = aleatorio.nextInt(Com1 - Com + 1) + Com;
    }
}

for( a = 0; a < matriz1.length; a++) {
    for( b = 0; b < matriz1[a].length; b++) {
        generarStringBuilder.append(Integer.toString(matriz1[a][b]) + " ");  
    }
    generarStringBuilder.append("\n");
} 


Numeros.setText(generarStringBuilder.toString());
        
        
        
        
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
      StringBuilder generarStringBuilder2 = new StringBuilder();
        for (int b = 0; b < matriz1[0].length; b++) {
    for (int a = 0; a < matriz1.length; a++) {
        generarStringBuilder2.append(Integer.toString(matriz1[a][b]) + " ");
    }
    generarStringBuilder2.append("\n");
    
}
     resul.setText(generarStringBuilder2.toString());    
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         StringBuilder generarStringBuilder1 = new StringBuilder();
     for (int a = 0; a < matriz1.length; a++) {
    if (a % 2 == 0) { 
        for (int b = matriz1[a].length - 1; b >= 0; b--) { 
            generarStringBuilder1.append(Integer.toString(matriz1[a][b]) + " ");
        }
    } else { 
        for (int b = 0; b < matriz1[a].length; b++) {
            generarStringBuilder1.append(Integer.toString(matriz1[a][b]) + " ");
        }
    }
    generarStringBuilder1.append("\n");
}
     resul.setText(generarStringBuilder1.toString());
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       limpiar1();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       StringBuilder generarStringBuilder3 = new StringBuilder();
    for (int a = 0; a < matriz1.length; a++) {
    if (a < 2) {
        for (int b = matriz1[a].length - 1; b >= 0; b--) {
            generarStringBuilder3.append(Integer.toString(matriz1[a][b]) + " ");
        }
    } else { 
        for (int b = 0; b < matriz1[a].length; b++) {
            generarStringBuilder3.append(Integer.toString(matriz1[a][b]) + " ");
        }
    }
    generarStringBuilder3.append("\n");
}
     resul.setText(generarStringBuilder3.toString());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     StringBuilder generarStringBuilder2 = new StringBuilder();
for (int b = 0; b < matriz1[0].length; b++) {
    if (b >= matriz1[0].length / 3 && b <= matriz1[0].length * 2 / 3) { 
        for (int a = matriz1.length - 1; a >= 0; a--) {
            generarStringBuilder2.append(Integer.toString(matriz1[a][b]) + " ");
        }
    } else if (b < matriz1[0].length / 3) {
        for (int a = 0; a < matriz1.length; a++) {
            generarStringBuilder2.append(Integer.toString(matriz1[a][b]) + " ");
        }
    } else {
        for (int a = matriz1.length - 1; a >= 0; a--) {
            generarStringBuilder2.append(Integer.toString(matriz1[a][b]) + " ");
        }
    }
    generarStringBuilder2.append("\n");
}
resul.setText(generarStringBuilder2.toString());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 StringBuilder generarStringBuilder3 = new StringBuilder();
for (int a = 0; a < matriz1.length; a++) {
    if (a % 3 == 0) {
        for (int b = 0; b < matriz1[a].length; b++) {
            generarStringBuilder3.append(Integer.toString(matriz1[a][b]));
            generarStringBuilder3.append(" ");
        }
    } else if (a % 3 == 1 || a % 3 == 2) {
        for (int b = matriz1[a].length - 1; b >= 0; b--) {
            generarStringBuilder3.append(Integer.toString(matriz1[a][b]));
            generarStringBuilder3.append(" ");
        }
    }
    generarStringBuilder3.append("\n");
}
resul.setText(generarStringBuilder3.toString());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       StringBuilder generarStringBuilder3 = new StringBuilder();
for (int a = 0; a < matriz1.length; a++) {
   
    boolean primerasDosColumnas = (a < 2);
    if (primerasDosColumnas) {
       
        for (int b = 0; b < matriz1[a].length; b++) {
            generarStringBuilder3.append(Integer.toString(matriz1[b][a]) + " ");
        }
    } else {
    
        for (int b = matriz1[a].length - 1; b >= 0; b--) {
            generarStringBuilder3.append(Integer.toString(matriz1[b][a]) + " ");
        }
    }
    generarStringBuilder3.append("\n");
}
resul.setText(generarStringBuilder3.toString());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       StringBuilder generarStringBuilder3 = new StringBuilder();

int inicioFila = 0;
int finFila = matriz1.length - 1;
int inicioColumna = 0;
int finColumna = matriz1[0].length - 1;

while (inicioFila <= finFila && inicioColumna <= finColumna) {
  
    for (int a = inicioColumna; a <= finColumna; a++) {
        generarStringBuilder3.append(Integer.toString(matriz1[inicioFila][a]) + " ");
    }
    inicioFila++;


    for (int a = inicioFila; a <= finFila; a++) {
        generarStringBuilder3.append(Integer.toString(matriz1[a][finColumna]) + " ");
    }
    finColumna--;


    if (inicioFila <= finFila) {
        for (int a = finColumna; a >= inicioColumna; a--) {
            generarStringBuilder3.append(Integer.toString(matriz1[finFila][a]) + " ");
        }
        finFila--;
    }

 
    if (inicioColumna <= finColumna) {
        for (int a = finFila; a >= inicioFila; a--) {
            generarStringBuilder3.append(Integer.toString(matriz1[a][inicioColumna]) + " ");
        }
        inicioColumna++;
    }
}

resul.setText(generarStringBuilder3.toString());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      StringBuilder generarStringBuilder3 = new StringBuilder();

int inicioFila = 0;
int finFila = matriz1.length - 1;
int inicioColumna = matriz1[0].length - 1;
int finColumna = 0;

while (inicioFila <= finFila && inicioColumna >= finColumna) {
        for (int a = inicioColumna; a >= finColumna; a--) {
        generarStringBuilder3.append(Integer.toString(matriz1[inicioFila][a]) + " ");
    }
    inicioFila++;

    for (int a = inicioFila; a <= finFila; a++) {
        generarStringBuilder3.append(Integer.toString(matriz1[a][finColumna]) + " ");
    }
    finColumna++;

    for (int a = finColumna; a <= inicioColumna; a++) {
        generarStringBuilder3.append(Integer.toString(matriz1[finFila][a]) + " ");
    }
    finFila--;

    for (int a = finFila; a >= inicioFila; a--) {
        generarStringBuilder3.append(Integer.toString(matriz1[a][inicioColumna]) + " ");
    }
    inicioColumna--;
}

resul.setText(generarStringBuilder3.toString());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
     StringBuilder generarStringBuilder4 = new StringBuilder();

int inicioFila = 0;
int finFila = matriz1.length - 1;
int inicioColumna = 0;
int finColumna = matriz1[0].length - 1;

while (inicioFila <= finFila && inicioColumna <= finColumna) {
   
    for (int a = inicioFila; a <= finFila; a++) {
        generarStringBuilder4.append(Integer.toString(matriz1[a][inicioColumna]) + " ");
    }
    inicioColumna++;

    for (int a = inicioColumna; a <= finColumna; a++) {
        generarStringBuilder4.append(Integer.toString(matriz1[finFila][a]) + " ");
    }
    finFila--;

    for (int a = finFila; a >= inicioFila; a--) {
        generarStringBuilder4.append(Integer.toString(matriz1[a][finColumna]) + " ");
    }
    finColumna--;

    for (int a = finColumna; a >= inicioColumna; a--) {
        generarStringBuilder4.append(Integer.toString(matriz1[inicioFila][a]) + " ");
    }
    inicioFila++;
}

String[] numeros = generarStringBuilder4.toString().split(" ");
Collections.reverse(Arrays.asList(numeros));
StringBuilder resultadoInvertido = new StringBuilder();
for (String numero : numeros) {
    resultadoInvertido.append(numero).append(" ");
}

resul.setText(resultadoInvertido.toString());

    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matriz().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JTextArea Numeros;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> matriz;
    private javax.swing.JTextField resul;
    // End of variables declaration//GEN-END:variables
private void limpiar(){
        L1.setText("");
        L2.setText("");
        Numeros.setText("");
        resul.setText("");
}
private void limpiar1(){
        resul.setText("");
}

}

